// Import Next.js font optimization utilities
import { Geist, Geist_Mono } from "next/font/google";
// Import global CSS styles
import "./globals.css";

/**
 * Configure Geist Sans font with:
 * - CSS variable name for reference
 * - Latin subset for optimal loading
 */
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable name
  subsets: ["latin"], // Character subset to preload
});

/**
 * Configure Geist Mono font with:
 * - CSS variable name for reference
 * - Latin subset for optimal loading
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable name
  subsets: ["latin"], // Character subset to preload
});

// Metadata for the application (used in head tags)
export const metadata = {
  title: "Create Next App", // Default page title
  description: "Generated by create next app", // Default page description
};

/**
 * Root layout component that wraps all pages
 * @param {Object} props - Component props
 * @param {React.ReactNode} props.children - Child components to render
 * @returns {JSX.Element} The root layout structure
 */
export default function RootLayout({ children }) {
  return (
    // HTML document with lang attribute for accessibility
    <html lang="en">
      {/* Body with font classes and antialiasing for smooth text */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Render child components (page content) */}
        {children}
      </body>
    </html>
  );
}